version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    command: ['./bin/rails', 'server', '-b', '0.0.0.0']

volumes:
  bundle_cache:
